-- MySQL Script generated by MySQL Workbench
-- Sat Sep 26 21:50:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modelatge_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelatge_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelatge_2` DEFAULT CHARACTER SET utf8mb4 ;
USE `modelatge_2` ;

-- -----------------------------------------------------
-- Table `modelatge_2`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelatge_2`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `street` VARCHAR(100) NULL,
  `number` VARCHAR(10) NULL,
  `flat` VARCHAR(10) NULL,
  `door` VARCHAR(10) NULL,
  `city` VARCHAR(45) NOT NULL,
  `postal code` INT(5) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSupplier`),
  UNIQUE INDEX `idSupplier_UNIQUE` (`idSupplier` ASC) VISIBLE,
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelatge_2`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelatge_2`.`Brand` (
  `idBrand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  PRIMARY KEY (`idBrand`),
  INDEX `fk_Brand_Supplier1_idx` (`Supplier_idSupplier` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `modelatge_2`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelatge_2`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelatge_2`.`Employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `phone` INT NOT NULL,
  PRIMARY KEY (`idEmployees`),
  UNIQUE INDEX `idEmployees_UNIQUE` (`idEmployees` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelatge_2`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelatge_2`.`Glasses` (
  `idGlasses` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(60) NOT NULL,
  `mount` CHAR(1) NOT NULL COMMENT 'tipus de muntura:\nF= flotant\nP= pasta\nM= metal·lica',
  `mount_colour` VARCHAR(45) NOT NULL,
  `glass_colour` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  `Employees_idEmployees` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  UNIQUE INDEX `idglasses_UNIQUE` (`idGlasses` ASC) VISIBLE,
  INDEX `fk_Glasses_Brand_idx` (`Brand_idBrand` ASC) VISIBLE,
  INDEX `fk_Glasses_Employees1_idx` (`Employees_idEmployees` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Brand`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `modelatge_2`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Employees1`
    FOREIGN KEY (`Employees_idEmployees`)
    REFERENCES `modelatge_2`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelatge_2`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelatge_2`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `adress` VARCHAR(200) NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `calib_right` DECIMAL(5,2) NOT NULL,
  `calib_left` DECIMAL(5,2) NOT NULL,
  `reg_date` DATETIME NOT NULL COMMENT 'data de registro en caso de nuevo cliente',
  `recom_client` VARCHAR(60) NULL,
  `Glasses_idGlasses` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Client_Glasses1_idx` (`Glasses_idGlasses` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Glasses1`
    FOREIGN KEY (`Glasses_idGlasses`)
    REFERENCES `modelatge_2`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
